import{auth,db}from"./firebase-config.js";import{onAuthStateChanged}from"https://www.gstatic.com/firebasejs/12.2.1/firebase-auth.js";import{collection,getDocs,query,where,doc,updateDoc,deleteDoc,getDoc,runTransaction,serverTimestamp}from"https://www.gstatic.com/firebasejs/12.2.1/firebase-firestore.js";
const ADMIN_EMAIL="admin@greatindia.technology",$=id=>document.getElementById(id),esc=x=>String(x??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
async function load(){
 const us=await getDocs(collection(db,"users")),apps=await getDocs(collection(db,"appHistory")),rs=await getDocs(query(collection(db,"adminRequests"),where("status","==","pending")));
 let blocked=0;us.forEach(x=>{if(x.data().blocked)blocked++});
 $("users").textContent=us.size;$("blocked").textContent=blocked;$("apps").textContent=apps.size;$("pending").textContent=rs.size;
 $("usersTable").innerHTML=us.empty?"No users.":`<table class="table"><thead><tr><th>Name</th><th>Email</th><th>UID</th><th>Status</th><th>Usage</th><th>Actions</th></tr></thead><tbody>${us.docs.map(x=>{const d=x.data();return `<tr><td>${esc(d.name||"")}</td><td>${esc(d.email||"")}</td><td class="muted">${esc(x.id)}</td><td>${d.blocked?"🚫 Blocked":"✅ Active"}</td><td>${Number(d.buildCount||0)} builds</td><td><button class="btn gray" onclick="editUser('${x.id}',${JSON.stringify(d.name||"")})">Edit</button><button class="btn ${d.blocked?"ok":"warn"}" onclick="toggleBlock('${x.id}',${!!d.blocked})">${d.blocked?"Unblock":"Block"}</button><button class="btn danger" onclick="deleteUserData('${x.id}')">Delete</button></td></tr>`}).join("")}</tbody></table>`;
 $("requests").innerHTML=rs.empty?"No pending requests.":rs.docs.map(x=>{const d=x.data();return `<div class="card"><b>${esc(d.name||"User")}</b> — ${esc(d.email||"")}<br><span class="muted">Requested extra: ${Number(d.requestedExtra||2)} · ${esc(d.message||"")}</span><br><button class="btn ok" onclick="approve('${x.id}',${Number(d.requestedExtra||2)})">Approve</button><button class="btn danger" onclick="reject('${x.id}')">Reject</button></div>`}).join("");
}
window.editUser=async(uid,current)=>{const name=prompt("User name:",current);if(name===null)return;await updateDoc(doc(db,"users",uid),{name:name.trim(),updatedAt:serverTimestamp()});await load()};
window.toggleBlock=async(uid,blocked)=>{await updateDoc(doc(db,"users",uid),{blocked:!blocked,updatedAt:serverTimestamp()});await load()};
window.deleteUserData=async uid=>{if(!confirm("Delete this user's Firestore profile, usage and app history? Firebase Auth account deletion needs Admin SDK/Cloud Function."))return;await deleteDoc(doc(db,"users",uid));await deleteDoc(doc(db,"usage",uid));await deleteDoc(doc(db,"adminRequests",uid));const apps=await getDocs(query(collection(db,"appHistory"),where("uid","==",uid)));await Promise.all(apps.docs.map(x=>deleteDoc(x.ref)));await load()};
window.approve=async(uid,extra)=>{const u=doc(db,"usage",uid),r=doc(db,"adminRequests",uid);await runTransaction(db,async tx=>{const s=await tx.get(u),d=s.exists()?s.data():{count:0,extra:0};tx.set(u,{uid,count:Number(d.count||0),extra:Number(d.extra||0)+extra,updatedAt:serverTimestamp()},{merge:true});tx.update(r,{status:"approved",approvedAt:serverTimestamp(),updatedAt:serverTimestamp()})});await load()};
window.reject=async uid=>{await updateDoc(doc(db,"adminRequests",uid),{status:"rejected",updatedAt:serverTimestamp()});await load()};
onAuthStateChanged(auth,async u=>{if(!u||String(u.email||"").toLowerCase()!==ADMIN_EMAIL){location.href="index.html";return}await load()});