import {auth,db} from "./firebase-config.js";
import {onAuthStateChanged,signOut} from "https://www.gstatic.com/firebasejs/12.2.1/firebase-auth.js";
import {doc,getDoc,addDoc,collection,serverTimestamp} from "https://www.gstatic.com/firebasejs/12.2.1/firebase-firestore.js";
const $=s=>document.querySelector(s),appId=new URLSearchParams(location.search).get("id"),autoBuild=new URLSearchParams(location.search).get("build")==="1";$("#logoutBtn")?.addEventListener("click",async()=>{await signOut(auth);location.href="./login.html"});
onAuthStateChanged(auth,async u=>{if(!u){location.href="./login.html";return}if(!appId){$("#detailsRoot").innerHTML='<div class="panel empty-state">Missing app ID.</div>';return}const s=await getDoc(doc(db,"apps",appId));if(!s.exists()||s.data().userId!==u.uid){$("#detailsRoot").innerHTML='<div class="panel empty-state">App not found.</div>';return}render({id:s.id,...s.data()});if(autoBuild)buildApp(s.id)});
function render(a){$("#detailsRoot").innerHTML=`<section class="details-hero"><div class="details-title"><div class="app-logo">${esc((a.appName||"GI").slice(0,2).toUpperCase())}</div><div><h2>${esc(a.appName)}</h2><p>${esc(a.websiteUrl)}</p><span class="status-badge ${a.status||"draft"}">${a.status||"draft"}</span></div></div><div class="details-actions"><a class="btn btn-ghost" href="./create-app.html?id=${encodeURIComponent(a.id)}">Edit App</a><button id="buildBtn" class="btn btn-primary">Build Android App</button></div></section><section class="details-grid"><div class="detail-item"><small>PACKAGE</small><strong>${esc(a.packageName)}</strong></div><div class="detail-item"><small>VERSION</small><strong>${esc(a.version)}</strong></div><div class="detail-item"><small>THEME</small><strong>${esc(a.theme)}</strong></div><div class="detail-item"><small>STATUS</small><strong>${esc(a.status||"draft")}</strong></div></section><section id="buildArea" class="build-box"><h3>Android build service</h3><p>Android build service is not connected yet.</p></section>`;$("#buildBtn").onclick=()=>buildApp(a.id)}
async function buildApp(id){const a=$("#buildArea"),b=$("#buildBtn");b.disabled=true;a.innerHTML="<h3>Android build service is not connected yet.</h3><p>No APK has been generated. Connect a secure backend/build server API for real APK builds.</p>";try{await addDoc(collection(db,"builds"),{appId:id,userId:auth.currentUser.uid,status:"waiting-backend",createdAt:serverTimestamp()})}catch(e){console.warn(e)}b.disabled=false}
export async function getBuildStatus(buildId){const s=await getDoc(doc(db,"builds",buildId));return s.exists()&&s.data().userId===auth.currentUser?.uid?{id:s.id,...s.data()}:null}
export async function downloadApk(buildId){const b=await getBuildStatus(buildId);if(!b?.downloadUrl){alert("No APK is available. Android build service is not connected yet.");return null}location.href=b.downloadUrl;return b.downloadUrl}
function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}