import { auth, db, firebaseConfigured } from "./firebase-config.js";
import { onAuthStateChanged, signOut } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-auth.js";
import { doc, getDoc, addDoc, collection, serverTimestamp } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-firestore.js";

const $=s=>document.querySelector(s), appId=new URLSearchParams(location.search).get("id"), autoBuild=new URLSearchParams(location.search).get("build")==="1";
function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function date(v){if(!v)return"—";const d=v.toDate?v.toDate():new Date(v);return isNaN(d)?"—":d.toLocaleString()}
function toast(t){const x=$("#toast");x.textContent=t;x.classList.add("show");setTimeout(()=>x.classList.remove("show"),3000)}
$("#logoutBtn")?.addEventListener("click",async()=>{if(auth)await signOut(auth);location.href="./login.html"});
$("#menuBtn")?.addEventListener("click",()=>document.querySelector(".sidebar")?.classList.toggle("mobile-open"));

if(auth)onAuthStateChanged(auth,async u=>{if(!u){location.href="./login.html";return}if(!firebaseConfigured){$("#detailsRoot").innerHTML='<div class="panel"><div class="empty-state"><strong>Firebase configuration required</strong><span>Paste your Firebase Web App config in <b>js/firebase-config.js</b> to load project data.</span></div></div>';return}if(!appId){$("#detailsRoot").innerHTML='<div class="panel"><div class="empty-state"><strong>Missing app ID</strong><span>Open an app from My Apps.</span></div></div>';return}await load(u.uid)});
async function load(uid){try{const s=await getDoc(doc(db,"apps",appId));if(!s.exists()||s.data().userId!==uid){$("#detailsRoot").innerHTML='<div class="panel"><div class="empty-state"><strong>App not found</strong><span>This project does not belong to your account.</span></div></div>';return}render({id:s.id,...s.data()},uid)}catch(e){console.error(e);$("#detailsRoot").innerHTML='<div class="panel"><div class="empty-state"><strong>Could not load app</strong><span>Check Firestore rules and Firebase configuration.</span></div></div>'}}
function render(a,uid){const logo=a.logoUrl?`<img class="app-logo" src="${esc(a.logoUrl)}" alt="">`:`<div class="app-logo">${esc((a.appName||"GI").slice(0,2).toUpperCase())}</div>`;$("#detailsRoot").innerHTML=`<section class="details-hero"><div class="details-title">${logo}<div><h2>${esc(a.appName||"Untitled App")}</h2><p>${esc(a.websiteUrl||"No website URL")}</p><span class="status-badge ${esc(a.status||"draft")}">${esc(a.status||"draft")}</span></div></div><div class="details-actions"><a class="btn btn-ghost" href="./create-app.html?id=${encodeURIComponent(a.id)}">Edit App</a><button id="buildBtn" class="btn btn-primary">Build Android App</button></div></section><section class="details-grid"><div class="detail-item"><small>PACKAGE NAME</small><strong>${esc(a.packageName)}</strong></div><div class="detail-item"><small>VERSION</small><strong>${esc(a.version)}</strong></div><div class="detail-item"><small>THEME</small><strong>${esc(a.theme)}</strong></div><div class="detail-item"><small>CREATED</small><strong>${date(a.createdAt)}</strong></div><div class="detail-item"><small>WEBSITE</small><strong>${esc(a.websiteUrl)}</strong></div><div class="detail-item"><small>STATUS</small><strong>${esc(a.status||"draft")}</strong></div></section><section id="buildArea" class="build-box" style="margin-top:18px"><h3>Android build service</h3><p>Connect a secure backend/build API later. This frontend will not pretend that GitHub Pages compiled an APK.</p></section>`;
$("#buildBtn").addEventListener("click",()=>buildApp(a.id));
if(autoBuild)setTimeout(()=>buildApp(a.id),250)}
export async function buildApp(id){const area=$("#buildArea"),btn=$("#buildBtn");btn.disabled=true;btn.textContent="Preparing…";area.innerHTML='<h3>Android build service is not connected yet.</h3><p>Demo Build Mode is active. No APK has been generated and nothing is available to download.</p><p><b>Next phase:</b> connect a secure backend/build server API here.</p>';if(firebaseConfigured&&auth.currentUser){try{const ref=await addDoc(collection(db,"builds"),{appId:id,userId:auth.currentUser.uid,status:"demo",mode:"demo",createdAt:serverTimestamp()});area.innerHTML+=`<p>Demo build request recorded: <code>${esc(ref.id)}</code></p>`}catch(e){console.warn(e)}}btn.disabled=false;btn.textContent="Build Android App";toast("Demo mode: no APK was generated.")}
export async function getBuildStatus(buildId){if(!firebaseConfigured||!auth?.currentUser)return null;const s=await getDoc(doc(db,"builds",buildId));if(!s.exists()||s.data().userId!==auth.currentUser.uid)return null;return {id:s.id,...s.data()}}
export async function downloadApk(buildId){const build=await getBuildStatus(buildId);if(!build||!build.downloadUrl){toast("No APK is available. A real build service must be connected first.");return null}window.open(build.downloadUrl,"_blank","noopener,noreferrer");return build.downloadUrl}
