import {auth,db,storage} from "./firebase-config.js";
import {onAuthStateChanged,signOut} from "https://www.gstatic.com/firebasejs/12.2.1/firebase-auth.js";
import {collection,addDoc,doc,getDoc,updateDoc,serverTimestamp} from "https://www.gstatic.com/firebasejs/12.2.1/firebase-firestore.js";
import {ref,uploadBytes,getDownloadURL} from "https://www.gstatic.com/firebasejs/12.2.1/firebase-storage.js";
const $=s=>document.querySelector(s),id=new URLSearchParams(location.search).get("id");$("#logoutBtn")?.addEventListener("click",async()=>{await signOut(auth);location.href="./login.html"});
let user;
onAuthStateChanged(auth,async u=>{if(!u){location.href="./login.html";return}user=u;if(id)loadEdit(u.uid)});
async function loadEdit(uid){const s=await getDoc(doc(db,"apps",id));if(!s.exists()||s.data().userId!==uid){$("#message").hidden=false;$("#message").textContent="App not found.";return}const a=s.data();$("#pageTitle").textContent="Edit App";$("#appName").value=a.appName||"";$("#websiteUrl").value=a.websiteUrl||"";$("#packageName").value=a.packageName||"";$("#version").value=a.version||"1.0.0";$("#theme").value=a.theme||"light"}
$("#appForm").onsubmit=async e=>{e.preventDefault();const b=$("#saveBtn");b.disabled=true;b.textContent="Saving…";try{new URL($("#websiteUrl").value);const data={userId:user.uid,appName:$("#appName").value.trim(),websiteUrl:$("#websiteUrl").value.trim(),packageName:$("#packageName").value.trim(),version:$("#version").value.trim(),theme:$("#theme").value,status:"draft",updatedAt:serverTimestamp()};for(const [field,path] of [["logoFile","logos"],["iconFile","icons"]]){const f=$("#"+field).files[0];if(f){const r=ref(storage,`${path}/${user.uid}/${Date.now()}-${f.name}`);await uploadBytes(r,f);data[field==="logoFile"?"logoUrl":"iconUrl"]=await getDownloadURL(r)}}if(id)await updateDoc(doc(db,"apps",id),data);else{data.createdAt=serverTimestamp();await addDoc(collection(db,"apps"),data)}location.href="./my-apps.html"}catch(x){const m=$("#message");m.hidden=false;m.className="message error";m.textContent=x.message||"Could not save app."}finally{b.disabled=false;b.textContent="Save App"}};
$("#previewBtn")?.addEventListener("click",()=>{try{alert(`App: ${$("#appName").value}\nWebsite: ${$("#websiteUrl").value}\nVersion: ${$("#version").value}`)}catch(e){}});